import xgboost as xgb
import pandas as pd
from sklearn.metrics import r2_score, mean_absolute_error

# 1. 데이터 로드
Final_df = pd.read_excel('/Users/SOO/Desktop/데분 포트폴리오/Data_Project/1. KBO 예측/2. 데이터 전처리/최종 데이터 정리/Final_KBO_Data.xlsx')

# 2. 내가 직접 선택한 변수 조합 리스트 (성능 0.7 이상으로 나온 조합 689개)
selected_combinations = [
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'OPS_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'OOB_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'AVG_hitter' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RBI_hitter', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'R_hitter', 'AVG_hitter', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RBI_hitter', 'AVG_hitter', 'SB_runner', 'SBA_runner' ],
    [ 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'SB_runner', 'OOB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RBI_hitter', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'E_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'E_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'R_hitter', 'AVG_hitter', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'E_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense', 'E_defense' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SBA_runner', 'OOB_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'CS%_defense', 'SB_runner', 'OOB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'AVG_pitcher', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'OOB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'OPS_hitter', 'R_hitter', 'FPCT_defense', 'CS%_defense' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'CS%_defense' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'E_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'RBI_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'E_defense', 'SB_runner' ],
    [ 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner', 'OOB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'CS_runner' ],
    [ 'WHIP_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'E_defense', 'SB_runner', 'CS_runner' ],
    [ 'OPS_hitter', 'RISP_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'E_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'E_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'E_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'SB_runner', 'SBA_runner' ],
    [ 'BPC_pitcher', 'PB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'OOB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'R_pitcher', 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'OOB_runner', 'CS_runner' ],
    [ 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'E_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'OPS_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'OOB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'CS%_defense' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'E_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'E_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RBI_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RBI_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'CS%_defense', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_runner', 'CS_runner' ],
    [ 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'SB_defense', 'E_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RBI_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'FPCT_defense', 'CS_runner' ],
    [ 'ERA_pitcher', 'RISP_hitter', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'SBA_runner', 'OOB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'SB_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'E_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_defense', 'SBA_runner' ],
    [ 'RISP_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'OOB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RBI_hitter', 'AVG_hitter', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'E_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'E_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RBI_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SBA_runner', 'OOB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'PB_defense', 'CS%_defense' ],
    [ 'BPC_pitcher', 'OPS_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RBI_hitter', 'FPCT_defense', 'SB_runner' ],
    [ 'R_pitcher', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RBI_hitter', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'R_hitter', 'RBI_hitter', 'FPCT_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'E_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'E_defense', 'PB_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense', 'E_defense', 'CS%_defense', 'SB_runner', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'E_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'PB_defense', 'SBA_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_runner' ],
    [ 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'CS%_defense' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'R_pitcher', 'BPC_pitcher', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'E_defense', 'PB_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'E_defense' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner', 'CS_runner' ],
    [ 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense', 'CS%_defense' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'E_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'E_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RBI_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'FPCT_defense', 'E_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'E_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'E_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'SB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense' ],
    [ 'WHIP_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'E_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'E_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'CS%_defense' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'E_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'RISP_hitter', 'R_hitter', 'SB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'PB_defense' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RBI_hitter', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'FPCT_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'AVG_hitter', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_hitter', 'SB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'SB_defense', 'E_defense', 'CS%_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense', 'PB_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'OPS_hitter', 'RBI_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'E_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'AVG_hitter', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_hitter', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner', 'OOB_runner' ],
    [ 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'R_hitter', 'RBI_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RBI_hitter', 'FPCT_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner', 'OOB_runner' ],
    [ 'OPS_hitter', 'CS%_defense', 'SBA_runner', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'R_pitcher', 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RBI_hitter', 'AVG_hitter', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_defense', 'E_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'E_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SBA_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'OOB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'RBI_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'E_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'SBA_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'R_hitter', 'AVG_hitter', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'E_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'R_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'RBI_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RBI_hitter', 'AVG_hitter', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'OPS_hitter', 'RBI_hitter', 'AVG_hitter', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'SB_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'R_hitter', 'AVG_hitter', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'CS%_defense', 'SB_runner', 'OOB_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'E_defense', 'SB_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_hitter', 'AVG_hitter', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'SB_defense', 'CS%_defense' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'OOB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense' ],
    [ 'WHIP_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'E_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'E_defense', 'SB_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_defense', 'SB_runner', 'OOB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'OOB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'SBA_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RBI_hitter', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'BPC_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'R_hitter', 'FPCT_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'R_hitter', 'PB_defense', 'SBA_runner' ],
    [ 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'R_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'AVG_pitcher', 'AVG_hitter', 'OOB_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'R_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_runner', 'SBA_runner' ],
    [ 'R_pitcher', 'R_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'E_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'OPS_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'OOB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'RBI_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'SB_defense', 'E_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner', 'OOB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'E_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'R_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RBI_hitter', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'CS%_defense' ],
    [ 'WHIP_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_defense', 'E_defense', 'CS%_defense', 'SB_runner', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'RBI_hitter', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'CS%_defense', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'AVG_hitter', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'OOB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'E_defense', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'CS_runner' ],
    [ 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SBA_runner', 'OOB_runner' ],
    [ 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense', 'PB_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'RBI_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'E_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'CS_runner' ],
    [ 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'FPCT_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'FPCT_defense', 'PB_defense', 'CS%_defense' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'E_defense', 'PB_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_defense', 'CS%_defense' ],
    [ 'ERA_pitcher', 'AVG_hitter', 'CS%_defense', 'SB_runner' ],
    [ 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'SB_runner', 'SBA_runner', 'OOB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner' ],
    [ 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'FPCT_defense', 'PB_defense', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'OPS_hitter', 'RBI_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'OPS_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'OOB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RBI_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'RBI_hitter', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'R_hitter', 'AVG_hitter', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SBA_runner', 'OOB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'SB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'FPCT_defense', 'E_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'E_defense', 'PB_defense', 'SBA_runner' ],
    [ 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'E_defense', 'CS%_defense', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RBI_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_defense', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RBI_hitter', 'CS%_defense' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'R_hitter', 'AVG_hitter', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'E_defense', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'PB_defense', 'CS%_defense', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'SB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SBA_runner', 'OOB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_defense', 'PB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'SB_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'SBA_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'E_defense', 'SB_runner' ],
    [ 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'R_hitter', 'FPCT_defense', 'SB_defense', 'SBA_runner' ],
    [ 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'OOB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'SB_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'OOB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'OOB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'AVG_hitter', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'CS%_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'OOB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'AVG_pitcher', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'CS%_defense', 'SB_runner', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'R_hitter', 'RBI_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_defense', 'E_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'OOB_runner' ],
    [ 'R_pitcher', 'R_hitter', 'FPCT_defense', 'SBA_runner', 'OOB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'E_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'CS%_defense', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner', 'OOB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'FPCT_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'R_hitter', 'E_defense', 'CS%_defense', 'SB_runner', 'OOB_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'E_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'BPC_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense' ],
    [ 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'RBI_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'E_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'CS%_defense', 'SB_runner', 'OOB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'AVG_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'AVG_hitter', 'PB_defense' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'CS_runner' ],
    [ 'WHIP_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'OOB_runner', 'CS_runner' ],
    [ 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'SB_defense', 'PB_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_defense', 'PB_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'OOB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'OPS_hitter', 'RISP_hitter', 'CS%_defense', 'CS_runner' ],
    [ 'AVG_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'R_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'E_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'RBI_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'SB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner' ],
    [ 'ERA_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'R_hitter', 'AVG_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'CS%_defense' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'E_defense', 'SB_runner', 'SBA_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'E_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_hitter', 'SB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'FPCT_defense', 'CS_runner' ],
    [ 'R_pitcher', 'AVG_pitcher', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'R_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'BPC_pitcher', 'OPS_hitter', 'AVG_hitter', 'FPCT_defense', 'E_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'E_defense', 'SB_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RBI_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'SB_defense', 'CS%_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'R_hitter', 'RBI_hitter', 'FPCT_defense' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'AVG_pitcher', 'OPS_hitter', 'E_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'PB_defense', 'CS%_defense', 'SBA_runner' ],
    [ 'R_pitcher', 'RISP_hitter', 'R_hitter', 'AVG_hitter', 'SB_defense', 'PB_defense', 'CS%_defense', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RBI_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'OPS_hitter', 'RBI_hitter', 'AVG_hitter', 'CS%_defense', 'SB_runner', 'SBA_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'R_hitter', 'FPCT_defense', 'SB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'OPS_hitter', 'FPCT_defense', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'OPS_hitter', 'RBI_hitter', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'BPC_pitcher', 'OPS_hitter', 'RISP_hitter', 'FPCT_defense', 'SB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'AVG_pitcher', 'R_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'RISP_hitter', 'RBI_hitter', 'AVG_hitter', 'PB_defense', 'SB_runner', 'SBA_runner', 'OOB_runner' ],
    [ 'WHIP_pitcher', 'ERA_pitcher', 'R_pitcher', 'BPC_pitcher', 'OPS_hitter', 'FPCT_defense', 'SB_defense', 'E_defense', 'CS%_defense', 'SB_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'SB_defense', 'E_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ],
    [ 'ERA_pitcher', 'R_pitcher', 'AVG_pitcher', 'OPS_hitter', 'RISP_hitter', 'AVG_hitter', 'FPCT_defense', 'PB_defense', 'CS%_defense', 'SBA_runner', 'CS_runner' ],
    [ 'WHIP_pitcher', 'R_pitcher', 'AVG_pitcher', 'BPC_pitcher', 'RISP_hitter', 'R_hitter', 'RBI_hitter', 'AVG_hitter', 'FPCT_defense', 'SB_defense', 'PB_defense', 'CS%_defense', 'SB_runner', 'SBA_runner', 'CS_runner' ]

]

# 3. 결과 저장을 위한 리스트 초기화
results_list = []

# 4. 선택한 조합별로 모델 학습 및 평가
for combo in selected_combinations:
    X_train = Final_df[Final_df['연도'] < 2023][combo]
    y_train = Final_df[Final_df['연도'] < 2023]['예측_승률']
    X_test = Final_df[Final_df['연도'] == 2023][combo]
    y_test = Final_df[Final_df['연도'] == 2024]['승률']

    # 모델 훈련
    model = xgb.XGBRegressor(n_estimators=100, max_depth=7)
    model.fit(X_train, y_train)

    # 성능 평가
    y_pred = model.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)

    # 결과 저장
    results_list.append({
        '변수_조합': '+'.join(combo),
        'R²': r2,
        'MAE': mae
    })

# 5. 결과 정리 및 저장
results_df = pd.DataFrame(results_list)
results_df = results_df.sort_values('R²', ascending=False)

# 결과 파일 저장
results_df.to_excel('선택한_변수조합_결과1.xlsx', index=False)
print("✅ 직접 선택한 변수 조합들의 모델 성능을 저장 완료!")
